name: CI

on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Login to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          justlogin: true
          
      - name: Export database info
        run: |
          heroku config:set USER=${{secrets.DB_USER}} -a ${{secrets.HEROKU_APP_NAME}}
          heroku config:set PASSWORD=${{secrets.DB_PASSWORD}} -a ${{secrets.HEROKU_APP_NAME}}
          heroku config:set HOST=${{secrets.DB_HOST}} -a ${{secrets.HEROKU_APP_NAME}}
          heroku config:set DB_PORT=${{secrets.DB_PORT}} -a ${{secrets.HEROKU_APP_NAME}}
          heroku config:set DB_NAME=${{secrets.DB_NAME}} -a ${{secrets.HEROKU_APP_NAME}}
          heroku config:set SECRET=${{secrets.FLASK_SECRET}} -a ${{secrets.HEROKU_APP_NAME}}

      - name: Push to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
